export const RESULTS_LOADING ='RESULTS_LOADING';
export const GIVE_RESULTS = 'GIVE_RESULTS';
export const RESULTS_FAILED = 'RESULTS_FAILED';

export const SEARCH_LOCATION = 'SEARCH_LOCATION';
export const SEARCH_FAILED = 'SEARCH_FAILED';


