export const BUSINESSES_LOADING ='BUSINESSES_LOADING';
export const GIVE_BUSINESSES = 'GIVE_BUSINESSES';
export const BUSINESSES_FAILED = 'BUSINESSES_FAILED';

export const SEARCH_LOCATION = 'SEARCH_LOCATION';
export const SEARCH_FAILED = 'SEARCH_FAILED';


